import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const MessageBox: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Private Mode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Private mode! (messagebox)</h1>
      </main>
    </div>
  );
};

export default MessageBox;
